export type AnimationFlag =
  | "LOOPING"
  | "HOLD_LAST_FRAME"
  | "REPOSITION_WHEN_FINISHED"
  | "NOT_INTERRUPTABLE"
  | "UPPERBODY"
  | "SECONDARY"
  | "REORIENT_WHEN_FINISHED"
  | "ABORT_ON_PED_MOVEMENT"
  | "ADDITIVE"
  | "TURN_OFF_COLLISION"
  | "OVERRIDE_PHYSICS"
  | "IGNORE_GRAVITY"
  | "EXTRACT_INITIAL_OFFSET"
  | "EXIT_AFTER_INTERRUPTED"
  | "TAG_SYNC_IN"
  | "TAG_SYNC_OUT"
  | "TAG_SYNC_CONTINUOUS"
  | "FORCE_START"
  | "USE_KINEMATIC_PHYSICS"
  | "USE_MOVER_EXTRACTION"
  | "HIDE_WEAPON"
  | "ENDS_IN_DEAD_POSE"
  | "ACTIVATE_RAGDOLL_ON_COLLISION"
  | "DONT_EXIT_ON_DEATH"
  | "ABORT_ON_WEAPON_DAMAGE"
  | "DISABLE_FORCED_PHYSICS_UPDATE"
  | "PROCESS_ATTACHMENTS_ON_START"
  | "EXPAND_PED_CAPSULE_FROM_SKELETON"
  | "USE_ALTERNATIVE_FP_ANIM"
  | "BLENDOUT_WRT_LAST_FRAME"
  | "USE_FULL_BLENDING";

export type AnimationChainData = {
  dictionary: string;
  name: string;
  flags: AnimationFlag[];
  duration?: number;
};
