CREATE TABLE
    IF NOT EXISTS head_overlays (
        id BIGSERIAL PRIMARY KEY,
        blemishes INT NOT NULL DEFAULT 255,
        blemishes_opacity FLOAT NOT NULL DEFAULT 1.0,
        facial_hair INT NOT NULL DEFAULT 255,
        facial_hair_color INT NOT NULL DEFAULT 1,
        facial_hair_second_color INT NOT NULL DEFAULT 1,
        facial_hair_opacity FLOAT NOT NULL DEFAULT 1.0,
        eyebrows INT NOT NULL DEFAULT 255,
        eyebrows_color INT NOT NULL DEFAULT 1,
        eyebrows_second_color INT NOT NULL DEFAULT 1,
        eyebrows_opacity FLOAT NOT NULL DEFAULT 1.0,
        ageing INT NOT NULL DEFAULT 255,
        ageing_opacity FLOAT NOT NULL DEFAULT 1.0,
        makeup INT NOT NULL DEFAULT 255,
        makeup_color INT NOT NULL DEFAULT 1,
        makeup_second_color INT NOT NULL DEFAULT 1,
        makeup_opacity FLOAT NOT NULL DEFAULT 1.0,
        blush INT NOT NULL DEFAULT 255,
        blush_color INT NOT NULL DEFAULT 1,
        blush_second_color INT NOT NULL DEFAULT 1,
        blush_opacity FLOAT NOT NULL DEFAULT 1.0,
        complexion INT NOT NULL DEFAULT 255,
        complexion_opacity FLOAT NOT NULL DEFAULT 1.0,
        sun_damage INT NOT NULL DEFAULT 255,
        sun_damage_opacity FLOAT NOT NULL DEFAULT 1.0,
        lipstick INT NOT NULL DEFAULT 255,
        lipstick_color INT NOT NULL DEFAULT 1,
        lipstick_second_color INT NOT NULL DEFAULT 1,
        lipstick_opacity FLOAT NOT NULL DEFAULT 1.0,
        moles_freckles INT NOT NULL DEFAULT 255,
        moles_freckles_color INT NOT NULL DEFAULT 1,
        moles_freckles_second_color INT NOT NULL DEFAULT 1,
        moles_freckles_opacity FLOAT NOT NULL DEFAULT 1.0,
        chest_hair INT NOT NULL DEFAULT 255,
        chest_hair_color INT NOT NULL DEFAULT 1,
        chest_hair_second_color INT NOT NULL DEFAULT 1,
        chest_hair_opacity FLOAT NOT NULL DEFAULT 1.0,
        body_blemishes INT NOT NULL DEFAULT 255,
        body_blemishes_opacity FLOAT NOT NULL DEFAULT 1.0,
        add_body_blemishes INT NOT NULL DEFAULT 255,
        add_body_blemishes_opacity FLOAT NOT NULL DEFAULT 1.0,
        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW (),
        updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW ()
    );

INSERT INTO
    head_overlays DEFAULT
VALUES;