CREATE TABLE
    IF NOT EXISTS component_variations (
        id BIGSERIAL PRIMARY KEY,
        face_drawable INT NOT NULL DEFAULT 0,
        face_texture INT NOT NULL DEFAULT 0,
        face_palette INT NOT NULL DEFAULT 0,
        mask_drawable INT NOT NULL DEFAULT 0,
        mask_texture INT NOT NULL DEFAULT 0,
        mask_palette INT NOT NULL DEFAULT 0,
        hair_drawable INT NOT NULL DEFAULT 0,
        hair_texture INT NOT NULL DEFAULT 0,
        hair_palette INT NOT NULL DEFAULT 0,
        torso_drawable INT NOT NULL DEFAULT 0,
        torso_texture INT NOT NULL DEFAULT 0,
        torso_palette INT NOT NULL DEFAULT 0,
        leg_drawable INT NOT NULL DEFAULT 0,
        leg_texture INT NOT NULL DEFAULT 0,
        leg_palette INT NOT NULL DEFAULT 0,
        bag_drawable INT NOT NULL DEFAULT 0,
        bag_texture INT NOT NULL DEFAULT 0,
        bag_palette INT NOT NULL DEFAULT 0,
        shoes_drawable INT NOT NULL DEFAULT 0,
        shoes_texture INT NOT NULL DEFAULT 0,
        shoes_palette INT NOT NULL DEFAULT 0,
        accessory_drawable INT NOT NULL DEFAULT 0,
        accessory_texture INT NOT NULL DEFAULT 0,
        accessory_palette INT NOT NULL DEFAULT 0,
        undershirt_drawable INT NOT NULL DEFAULT 0,
        undershirt_texture INT NOT NULL DEFAULT 0,
        undershirt_palette INT NOT NULL DEFAULT 0,
        kevlar_drawable INT NOT NULL DEFAULT 0,
        kevlar_texture INT NOT NULL DEFAULT 0,
        kevlar_palette INT NOT NULL DEFAULT 0,
        badge_drawable INT NOT NULL DEFAULT 0,
        badge_texture INT NOT NULL DEFAULT 0,
        badge_palette INT NOT NULL DEFAULT 0,
        torso_second_drawable INT NOT NULL DEFAULT 0,
        torso_second_texture INT NOT NULL DEFAULT 0,
        torso_second_palette INT NOT NULL DEFAULT 0,
        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW (),
        updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW ()
    );

INSERT INTO
    component_variations DEFAULT
VALUES;