allowBuilds:
  "@parcel/watcher": true
  esbuild: true

packages:
  - "src/core/client"
  - "src/core/server"
  - "src/db/server"
  - "src/map/client"
  - "src/nui/client"
  - "src/nui/frontend"
  - "src/types"
