allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true

packages:
  - "core/client"
  - "core/server"
  - "db/server"
  - "map/client"
  - "nui/client"
  - "nui/frontend"
  - "types"
