export const zonesMapping: Record<string, string> = {
  AIRP: "Международный аэропорт Лос-Сантос",
  ALAMO: "Аламо Си",
  ALTA: "Альта",
  ARMYB: "Форт Занкудо",
  BANHAMC: "Каньон Бэнхам",
  BANNING: "Бэннинг",
  BEACH: "Пляж Веспуччи",
  BHAMCA: "Каньон Бэнхам",
  BRADP: "Проезд Брэддок",
  BRADT: "Тоннель Брэддок",
  BURTON: "Бертон",
  CALAFB: "Мост Калафия",
  CANNY: "Каньон Ратон",
  CCREAK: "Кэссиди Крик",
  CHAMH: "Чамберлейн Хилз",
  CHIL: "Вайнвуд Хилз",
  CHU: "Чумаш",
  CMSW: "Заповедник горы Чилиад",
  CYPRE: "Сайпресс Флэтс",
  DAVIS: "Дэвис",
  DELBE: "Пляж Дель Пьерро",
  DELPE: "Дель Пьерро",
  DELSOL: "Ла Пуэрта",
  DESRT: "Пустыня Гранд Сенора",
  DOWNT: "Центр",
  DTVINE: "Центральный Вайнвуд",
  EAST_V: "Востчный Вайнвуд",
  EBURO: "Эль Бурро Хайтс",
  ELGORL: "Маяк Эль Гордо",
  ELYSIAN: "Элизиан Айленд",
  GALFISH: "Галилео",
  GOLF: "Гольф-клуб",
  GRAPES: "Грейпсид",
  GREATC: "Большой Чапараль",
  HARMO: "Хармони",
  HAWICK: "Хавик",
  HORS: "Трасса Вайнвуд",
  HUMLAB: "Хьюман Лабс",
  JAIL: "Тюрьма Болингбрук",
  KOREAT: "Маленький Сеул",
  LACT: "Резервуар",
  LAGO: "Лаго Занкудо",
  LDAM: "Дамба",
  LEGSQU: "Площадь Легиона",
  LMESA: "Ла Меса",
  LOSPUER: "Ла Пуерта",
  MIRR: "Миррор Парк",
  MORN: "Морнингвуд",
  MOVIE: "Ричардс Маджестик",
  MTCHIL: "Гора Чилиад",
  MTGORDO: "Гора Гордо",
  MTJOSE: "Гора Джосайя",
  MURRI: "Мурьета Хайтс",
  NCHU: "Северный Чумаш",
  NOOSE: "Н.У.П.",
  OCEANA: "Пасифик-Оушн",
  PALCOV: "Бухта Палето",
  PALETO: "Палето Бэй",
  PALFOR: "Лес Палето",
  PALHIGH: "Высокогорье Паломино",
  PALMPOW: "Электростанция",
  PBLUFF: "Пасифик-Блаффс",
  PBOX: "Пиллбокс Хилз",
  PROCOB: "Пляж Прокопио",
  RANCHO: "Ранчо",
  RGLEN: "Ричман Глен",
  RICHM: "Ричман",
  ROCKF: "Рокфорд Хилз",
  RTRAK: "Трасса Редвуд",
  SANAND: "Сан Андреас",
  SANCHIA: "Горный хребет Сан-Чиански",
  SANDY: "Сэнди Шорс",
  SKID: "Мишн Роу",
  SLAB: "Стаб Сити",
  STAD: "Мейз Банк Арена",
  STRAW: "Строберри",
  TATAMO: "Татавиамские горы",
  TERMINA: "Терминал",
  TEXTI: "Текстайл Сити",
  TONGVAH: "Тонгва Хилз",
  TONGVAV: "Долина Тонгва",
  VCANA: "Каналы Веспуччи",
  VESP: "Веспуччи",
  VINE: "Вайнвуд",
  WINDF: "Ветряная электростанция",
  WVINE: "Западный Вайнвуд",
  ZANCUDO: "Река Занкудо",
  ZP_ORT: "Порт Лос Сантоса",
  ZQ_UAR: "Дэвис Кварц",
};

type MarkerData = {
  type: number;
  coords: { x: number; y: number; z: number };
  action: CallableFunction;
  size: "small" | "medium" | "large";
  color: { red: number; green: number; blue: number; alpha: number };
  label?: string;
  helpText?: string;
};

const exports = global.exports as CitizenExports;

export const markers: MarkerData[] = [
  {
    label: "Clothes Shop #1",
    type: 1,
    coords: {
      x: 124.2783432006836,
      y: -224.8079833984375,
      z: 54.5578498840332,
    },
    action: () => exports.civil_nui.openPage("characterCreatorGenetics"),
    size: "medium",
    color: { red: 255, green: 255, blue: 255, alpha: 191 },
    helpText: "Press to interact",
  },
  {
    label: "Clothes Shop #2",
    type: 1,
    coords: {
      x: -703.8528442382812,
      y: -152.1354217529297,
      z: 37.41512680053711,
    },
    action: () => exports.civil_nui.openPage("characterCreatorGenetics"),
    size: "large",
    color: { red: 255, green: 255, blue: 255, alpha: 191 },
    helpText: "Press to interact",
  },
  {
    label: "Clothes Shop #3",
    type: 1,
    coords: {
      x: 76.840576171875,
      y: -1390.8724365234375,
      z: 29.37615203857422,
    },
    action: () => exports.civil_nui.openPage("characterCreatorGenetics"),
    size: "medium",
    color: { red: 255, green: 255, blue: 255, alpha: 191 },
    helpText: "Press to interact",
  },
];
