export type HeadBlends = {
  id: number;
  shape_first_id: number;
  shape_second_id: number;
  shape_third_id: number;
  skin_first_id: number;
  skin_second_id: number;
  skin_third_id: number;
  shape_mix: number;
  skin_mix: number;
  third_mix: number;
  created_at: string;
  updated_at: string;
};

export type FaceFeatures = {
  id: number;
  nose_width: number;
  nose_peak: number;
  nose_length: number;
  nose_bone_curveness: number;
  nose_tip: number;
  nose_bone_twist: number;
  eyebrow_up_down: number;
  eyebrow_in_out: number;
  cheek_bones: number;
  cheek_sideways_bone_size: number;
  cheek_bones_width: number;
  eye_opening: number;
  lip_thickness: number;
  jaw_bone_width: number;
  jaw_bone_shape: number;
  chin_bone: number;
  chin_bone_length: number;
  chin_bone_shape: number;
  chin_hole: number;
  neck_thickness: number;
  created_at: string;
  updated_at: string;
};

export type Skills = {
  id: number;
  stamina: number;
  strength: number;
  lung_capacity: number;
  wheelie_ability: number;
  flying_ability: number;
  shooting_ability: number;
  stealth_ability: number;
};

export type HeadOverlays = {
  id: number;
  blemishes: number;
  blemishes_opacity: number;
  facial_hair: number;
  facial_hair_color: number;
  facial_hair_second_color: number;
  facial_hair_opacity: number;
  eyebrows: number;
  eyebrows_color: number;
  eyebrows_second_color: number;
  eyebrows_opacity: number;
  ageing: number;
  ageing_opacity: number;
  makeup: number;
  makeup_color: number;
  makeup_second_color: number;
  makeup_opacity: number;
  blush: number;
  blush_color: number;
  blush_second_color: number;
  blush_opacity: number;
  complexion: number;
  complexion_opacity: number;
  sun_damage: number;
  sun_damage_opacity: number;
  lipstick: number;
  lipstick_color: number;
  lipstick_second_color: number;
  lipstick_opacity: number;
  moles_freckles: number;
  moles_freckles_color: number;
  moles_freckles_second_color: number;
  moles_freckles_opacity: number;
  chest_hair: number;
  chest_hair_color: number;
  chest_hair_second_color: number;
  chest_hair_opacity: number;
  body_blemishes: number;
  body_blemishes_opacity: number;
  add_body_blemishes: number;
  add_body_blemishes_opacity: number;
  created_at: string;
  updated_at: string;
};

export type ComponentVariations = {
  id: number;
  face_drawable: number;
  face_texture: number;
  face_palette: number;
  mask_drawable: number;
  mask_texture: number;
  mask_palette: number;
  hair_drawable: number;
  hair_texture: number;
  hair_palette: number;
  torso_drawable: number;
  torso_texture: number;
  torso_palette: number;
  leg_drawable: number;
  leg_texture: number;
  leg_palette: number;
  bag_drawable: number;
  bag_texture: number;
  bag_palette: number;
  shoes_drawable: number;
  shoes_texture: number;
  shoes_palette: number;
  accessory_drawable: number;
  accessory_texture: number;
  accessory_palette: number;
  undershirt_drawable: number;
  undershirt_texture: number;
  undershirt_palette: number;
  kevlar_drawable: number;
  kevlar_texture: number;
  kevlar_palette: number;
  badge_drawable: number;
  badge_texture: number;
  badge_palette: number;
  torso_second_drawable: number;
  torso_second_texture: number;
  torso_second_palette: number;
  created_at: string;
  updated_at: string;
};

export type Character = {
  id: number;
  firstname: string;
  lastname: string;
  age: number;
  sex: boolean;
  health: number;
  max_health: number;
  armour: number;
  max_armour: number;
  eye_color: number;
  hair_first_color: number;
  head_blends_id: number;
  face_features_id: number;
  skills_id: number;
  component_variations_id: number;
  head_overlays_id: number;
  last_position: {
    x: number;
    y: number;
    z: number;
    heading: number;
  };
  model: string;
  created_at: string;
  updated_at: string;
  head_blends: HeadBlends;
  face_features: FaceFeatures;
  skills: Skills;
  head_overlays: HeadOverlays;
  component_variations: ComponentVariations;
};
